# Financial Time Series Analysis

## Context:
You have an array of daily closing prices for a stock over a month (30 days).

## Input Data:
A 1D NumPy array, for example:

```python
closing_prices = np.array([100.5, 101.2, 102.3, 99.8, 100.0, 101.5, 102.8, 103.0, 102.0, 101.0,
                            100.8, 102.5, 103.2, 104.0, 103.5, 102.7, 101.9, 102.2, 103.1, 104.5,
                            105.0, 104.2, 103.8, 104.0, 105.5, 106.2, 105.8, 105.0, 104.5, 105.0])
```

## Tasks:

### 1. Moving Average Calculation:
- Compute a 5-day moving average.
- For the first 4 days, you can either leave the moving average undefined (or use `np.nan`) or start from day 5.

### 2. Price Comparison:
- Create a boolean mask indicating on which days the closing price is higher than the moving average (for days where the moving average is computed).

### 3. Percentage Change (Bonus):
- Calculate the percentage change between each consecutive day using the formula:
  
  $$
  \text{pct\_change} = \frac{\text{price}_i - \text{price}_{i-1}}{\text{price}_{i-1}} \times 100
  $$
  
- The first day can be marked as `np.nan` since there is no previous day.

### 4. Cumulative Return (Bonus):
- Calculate the cumulative return over the 30 days, showing the total percentage growth from Day 1 to each subsequent day using the formula:
  
  $$
  \text{cumulative\_return}_i = \frac{\text{price}_i - \text{price}_0}{\text{price}_0} \times 100
  $$
  
- Day 1 (index 0) has a cumulative return of 0% since it’s the starting point.

## Expected Output:
- An array of moving averages (same length as `closing_prices` with the first few values as `np.nan` if not computed).
- A boolean array indicating days where the closing price exceeds the moving average.
- An array of percentage changes between consecutive days.
- An array of cumulative returns from Day 1 to the last day.

In [1]:
import numpy as np

In [2]:
closing_prices = np.array([100.5, 101.2, 102.3, 99.8, 100.0, 101.5, 102.8, 103.0, 102.0, 101.0,
                            100.8, 102.5, 103.2, 104.0, 103.5, 102.7, 101.9, 102.2, 103.1, 104.5,
                            105.0, 104.2, 103.8, 104.0, 105.5, 106.2, 105.8, 105.0, 104.5, 105.0])

# 1. Moving Average Calculation:

In [3]:
moving_avg= np.full_like(closing_prices,np.nan)
moving_avg

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [5]:
for i in range(4,len(closing_prices)):
    moving_avg[i]=np.mean(closing_prices[i-4:i+1])
moving_avg

array([   nan,    nan,    nan,    nan, 100.76, 100.96, 101.28, 101.42,
       101.86, 102.06, 101.92, 101.86, 101.9 , 102.3 , 102.8 , 103.18,
       103.06, 102.86, 102.68, 102.88, 103.34, 103.8 , 104.12, 104.3 ,
       104.5 , 104.74, 105.06, 105.3 , 105.4 , 105.3 ])

# 2. Price Comparison:

In [7]:
closing_prices>moving_avg

array([False, False, False, False, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False, False, False])

In [12]:
# days on which closing price are greater than the moving average :

indices = np.where(closing_prices > moving_avg)[0]
days_above = np.array([f"day-{i+1}" for i in indices])
days_above

array(['day-6', 'day-7', 'day-8', 'day-9', 'day-12', 'day-13', 'day-14',
       'day-15', 'day-19', 'day-20', 'day-21', 'day-22', 'day-25',
       'day-26', 'day-27'], dtype='<U6')

# 3. Percentage Change (Bonus):

In [13]:
# re-pritingin the array
closing_prices

array([100.5, 101.2, 102.3,  99.8, 100. , 101.5, 102.8, 103. , 102. ,
       101. , 100.8, 102.5, 103.2, 104. , 103.5, 102.7, 101.9, 102.2,
       103.1, 104.5, 105. , 104.2, 103.8, 104. , 105.5, 106.2, 105.8,
       105. , 104.5, 105. ])

In [48]:
percentage_change_arr= np.concatenate( ( np.array([np.nan]) , np.diff(closing_prices)/closing_prices[:-1] *100 ) )
percentage_change_arr 

array([        nan,  0.69651741,  1.08695652, -2.44379277,  0.2004008 ,
        1.5       ,  1.28078818,  0.19455253, -0.97087379, -0.98039216,
       -0.1980198 ,  1.68650794,  0.68292683,  0.7751938 , -0.48076923,
       -0.77294686, -0.77896787,  0.29440628,  0.88062622,  1.35790495,
        0.4784689 , -0.76190476, -0.38387716,  0.19267823,  1.44230769,
        0.66350711, -0.37664783, -0.75614367, -0.47619048,  0.4784689 ])

# 4. Cumulative Return (Bonus):

In [52]:
cumulative_rturn= np.divide(closing_prices- closing_prices[0],closing_prices[0])*100
cumulative_rturn

array([ 0.        ,  0.69651741,  1.79104478, -0.69651741, -0.49751244,
        0.99502488,  2.28855721,  2.48756219,  1.49253731,  0.49751244,
        0.29850746,  1.99004975,  2.68656716,  3.48258706,  2.98507463,
        2.18905473,  1.39303483,  1.69154229,  2.58706468,  3.9800995 ,
        4.47761194,  3.68159204,  3.28358209,  3.48258706,  4.97512438,
        5.67164179,  5.27363184,  4.47761194,  3.9800995 ,  4.47761194])

# Days with positive percentage change

In [65]:
np.array([ f"day-{i+1}" for i in np.where(percentage_change_arr>0)[0] ])

array(['day-2', 'day-3', 'day-5', 'day-6', 'day-7', 'day-8', 'day-12',
       'day-13', 'day-14', 'day-18', 'day-19', 'day-20', 'day-21',
       'day-24', 'day-25', 'day-26', 'day-30'], dtype='<U6')

# Days feasible to sell with profit percentage and amnt
### Return type: column matrix where colum1 represents the day, column 2 represents the % and colmun 3 reperesnets the profit amnt

In [90]:
np.array(
    [   [ index+1, item, closing_prices[0]*item/100]
        for index,item in enumerate(cumulative_rturn.round(2))
        if item > 0
    ]
    ,dtype='float32'
)

array([[ 2.     ,  0.7    ,  0.7035 ],
       [ 3.     ,  1.79   ,  1.79895],
       [ 6.     ,  1.     ,  1.005  ],
       [ 7.     ,  2.29   ,  2.30145],
       [ 8.     ,  2.49   ,  2.50245],
       [ 9.     ,  1.49   ,  1.49745],
       [10.     ,  0.5    ,  0.5025 ],
       [11.     ,  0.3    ,  0.3015 ],
       [12.     ,  1.99   ,  1.99995],
       [13.     ,  2.69   ,  2.70345],
       [14.     ,  3.48   ,  3.4974 ],
       [15.     ,  2.99   ,  3.00495],
       [16.     ,  2.19   ,  2.20095],
       [17.     ,  1.39   ,  1.39695],
       [18.     ,  1.69   ,  1.69845],
       [19.     ,  2.59   ,  2.60295],
       [20.     ,  3.98   ,  3.9999 ],
       [21.     ,  4.48   ,  4.5024 ],
       [22.     ,  3.68   ,  3.6984 ],
       [23.     ,  3.28   ,  3.2964 ],
       [24.     ,  3.48   ,  3.4974 ],
       [25.     ,  4.98   ,  5.0049 ],
       [26.     ,  5.67   ,  5.69835],
       [27.     ,  5.27   ,  5.29635],
       [28.     ,  4.48   ,  4.5024 ],
       [29.     ,  3.98  

In [112]:
cumulative_rturn_rounded = cumulative_rturn.round(2)
print(f"the best day to sell was on day {np.where(cumulative_rturn_rounded == np.max(cumulative_rturn_rounded))[0][0] + 1}")

the best day to sell was on day 26
