# Weather Data Insights

## Context:
A research team collected temperature data from multiple sensors over a 30-day period. Each row represents one day, and each column represents a different sensor (assume 5 sensors).

## Input Data:
A 2D NumPy array (30 x 5), for example:

```python
temperatures = np.array([
    [22.1, 21.9, 22.5, 22.0, 21.8],
    [22.3, 22.1, 22.6, 22.2, 22.0],
    # ... 28 more days of data
])
```
(For practice, you can generate this data using `np.random.uniform` within a realistic range, e.g., 20°C to 25°C.)

## Tasks:

### 1. Daily Average Temperature:
- Calculate the average temperature for each day.

### 2. Extreme Temperature Detection:
- Identify the overall maximum and minimum temperatures in the dataset.
- Report the day index (row) and sensor index (column) for these extreme values.

### 3. Unit Conversion with Broadcasting:
- Convert the entire temperature array from Celsius to Fahrenheit using the formula:
  
  $$
  \text{Fahrenheit} = \text{Celsius} \times \frac{9}{5} + 32
  $$
  
- Output the converted array.

### 4. Rolling Window Temperature Trends:
- Compute a 3-day rolling average temperature for each sensor, where the average is taken over a window of 3 consecutive days (current day and the 2 previous days).
- For days with insufficient prior data (Days 0 and 1), fill with `np.nan`.
- Output a \(30 \times 5\) array with the rolling averages.

### 5. Temperature Gradient Analysis:
- Calculate the daily temperature gradient for each sensor, defined as the difference between the maximum and minimum temperatures recorded by that sensor up to and including the current day.
- Output a \(30 \times 5\) array where each element is the gradient for that sensor up to that day (for Day 0, it’s the range within that day; for Day 1, it’s the range across Days 0-1, etc.).

### 6. Sensor Consistency Ranking:
- Define a sensor’s "consistency" as the inverse of the standard deviation of its temperature readings over the 30 days (i.e., lower variation = higher consistency).
- Rank the sensors from most consistent (1) to least consistent (5).
- Handle ties by assigning the average rank to tied sensors.
- Output a 1D array of ranks (length = 5).


In [79]:
import numpy as np

# Set random seed for reproducibility (optional)
np.random.seed(42)

# Generate realistic temperature data
# Base temperature around 22°C, with daily variation (±2°C) and hourly variation (±0.5°C)
days = 30  # 30 days
measurements_per_day = 5  # 5 measurements per day

# Create base daily temperatures (mean temp for each day)
base_temps = np.random.uniform(20, 24, size=days)  # Random base between 20°C and 24°C

# Add variation for each measurement within the day
temperatures = np.array([
    base_temps[day] + np.random.uniform(-0.5, 0.5, size=measurements_per_day)
    for day in range(days)
])

# Round to 1 decimal place for realism (like your example)
temperatures = np.round(temperatures, decimals=1)

# Print the result
print("Temperatures (30 days, 5 measurements per day):")
print(temperatures)
temperatures.shape

Temperatures (30 days, 5 measurements per day):
[[21.6 21.2 21.1 21.9 22. ]
 [24.1 23.6 23.4 24.  23.7]
 [22.6 22.9 22.5 23.3 22.7]
 [22.6 22.2 22.4 22.4 22.1]
 [21.1 20.9 21.1 21.  20.7]
 [21.  20.2 20.3 20.2 20.4]
 [20.1 20.  20.6 20.1 20. ]
 [23.5 23.1 23.8 23.  24. ]
 [22.7 22.1 21.9 22.7 22.6]
 [23.1 23.1 22.4 22.7 22.4]
 [20.4 20.2 19.9 19.6 19.9]
 [23.7 24.1 24.  24.3 23.9]
 [22.9 23.5 23.6 23.4 23.6]
 [20.8 20.9 20.8 20.4 20.5]
 [20.3 20.9 20.5 20.7 21.1]
 [20.5 20.6 21.  20.5 20.3]
 [21.  20.9 21.6 21.5 21.4]
 [22.5 22.4 21.8 22.5 22.1]
 [22.  22.1 21.5 21.3 21.5]
 [21.1 21.5 21.5 20.7 21.2]
 [22.4 22.2 22.1 22.3 22.9]
 [20.4 20.6 20.8 20.4 21. ]
 [21.6 20.9 21.2 21.  21. ]
 [21.  21.6 21.5 21.  21.2]
 [22.2 21.6 21.5 21.8 22.3]
 [22.9 23.3 23.4 22.9 23.4]
 [20.7 20.9 20.9 20.8 20.4]
 [22.4 21.9 21.7 21.6 22.1]
 [22.5 21.9 22.4 22.1 22.5]
 [19.9 20.4 20.1 20.6 19.8]]


(30, 5)

# 1. Daily Average Temperature:

In [80]:
daily_avg= np.mean(temperatures,axis=1)
daily_avg

array([21.56, 23.76, 22.8 , 22.34, 20.96, 20.42, 20.16, 23.48, 22.4 ,
       22.74, 20.  , 24.  , 23.4 , 20.68, 20.7 , 20.58, 21.28, 22.26,
       21.68, 21.2 , 22.38, 20.64, 21.14, 21.26, 21.88, 23.18, 20.74,
       21.94, 22.28, 20.16])

# 2. Extreme Temperature Detection:


## overall maximum and minimum temperatures in the dataset.


In [81]:
max_temp=np.max(temperatures)
max_temp

24.3

In [82]:
min_temp=np.min(temperatures)
min_temp

19.6

## Report the day index (row)

In [83]:
max_temp_indices=np.where(temperatures==max_temp)
print(max_temp_indices)
min_temp_indices=np.where(temperatures==min_temp)
min_temp_indices

(array([11], dtype=int64), array([3], dtype=int64))


(array([10], dtype=int64), array([3], dtype=int64))

In [84]:
print(f"Max temp on day {max_temp_indices[0][0]+1} with value {max_temp} °C")
print(f"min temp on day {min_temp_indices[0][0]+1} with value {min_temp} °C")


Max temp on day 12 with value 24.3 °C
min temp on day 11 with value 19.6 °C


# 3. Unit Conversion with Broadcasting:

In [85]:
F_temp_arr= (temperatures*9/5)+32
F_temp_arr

array([[70.88, 70.16, 69.98, 71.42, 71.6 ],
       [75.38, 74.48, 74.12, 75.2 , 74.66],
       [72.68, 73.22, 72.5 , 73.94, 72.86],
       [72.68, 71.96, 72.32, 72.32, 71.78],
       [69.98, 69.62, 69.98, 69.8 , 69.26],
       [69.8 , 68.36, 68.54, 68.36, 68.72],
       [68.18, 68.  , 69.08, 68.18, 68.  ],
       [74.3 , 73.58, 74.84, 73.4 , 75.2 ],
       [72.86, 71.78, 71.42, 72.86, 72.68],
       [73.58, 73.58, 72.32, 72.86, 72.32],
       [68.72, 68.36, 67.82, 67.28, 67.82],
       [74.66, 75.38, 75.2 , 75.74, 75.02],
       [73.22, 74.3 , 74.48, 74.12, 74.48],
       [69.44, 69.62, 69.44, 68.72, 68.9 ],
       [68.54, 69.62, 68.9 , 69.26, 69.98],
       [68.9 , 69.08, 69.8 , 68.9 , 68.54],
       [69.8 , 69.62, 70.88, 70.7 , 70.52],
       [72.5 , 72.32, 71.24, 72.5 , 71.78],
       [71.6 , 71.78, 70.7 , 70.34, 70.7 ],
       [69.98, 70.7 , 70.7 , 69.26, 70.16],
       [72.32, 71.96, 71.78, 72.14, 73.22],
       [68.72, 69.08, 69.44, 68.72, 69.8 ],
       [70.88, 69.62, 70.16, 69.

# 3-day rolling average temperature



In [86]:
rolling_avg=np.full_like(temperatures,np.nan)

In [87]:
for i in range(2,temperatures.shape[0]):
    rolling_avg[i]= np.mean(temperatures[i-2:i+1],axis=0)

print(rolling_avg.shape)
rolling_avg

(30, 5)


array([[        nan,         nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan],
       [22.76666667, 22.56666667, 22.33333333, 23.06666667, 22.8       ],
       [23.1       , 22.9       , 22.76666667, 23.23333333, 22.83333333],
       [22.1       , 22.        , 22.        , 22.23333333, 21.83333333],
       [21.56666667, 21.1       , 21.26666667, 21.2       , 21.06666667],
       [20.73333333, 20.36666667, 20.66666667, 20.43333333, 20.36666667],
       [21.53333333, 21.1       , 21.56666667, 21.1       , 21.46666667],
       [22.1       , 21.73333333, 22.1       , 21.93333333, 22.2       ],
       [23.1       , 22.76666667, 22.7       , 22.8       , 23.        ],
       [22.06666667, 21.8       , 21.4       , 21.66666667, 21.63333333],
       [22.4       , 22.46666667, 22.1       , 22.2       , 22.06666667],
       [22.33333333, 22.6       , 22.5       , 22.43333333, 22.46666667],
       [22.46666667, 22.83333333, 22.8

# 5. Temperature Gradient Analysis:

In [88]:
temperatures

array([[21.6, 21.2, 21.1, 21.9, 22. ],
       [24.1, 23.6, 23.4, 24. , 23.7],
       [22.6, 22.9, 22.5, 23.3, 22.7],
       [22.6, 22.2, 22.4, 22.4, 22.1],
       [21.1, 20.9, 21.1, 21. , 20.7],
       [21. , 20.2, 20.3, 20.2, 20.4],
       [20.1, 20. , 20.6, 20.1, 20. ],
       [23.5, 23.1, 23.8, 23. , 24. ],
       [22.7, 22.1, 21.9, 22.7, 22.6],
       [23.1, 23.1, 22.4, 22.7, 22.4],
       [20.4, 20.2, 19.9, 19.6, 19.9],
       [23.7, 24.1, 24. , 24.3, 23.9],
       [22.9, 23.5, 23.6, 23.4, 23.6],
       [20.8, 20.9, 20.8, 20.4, 20.5],
       [20.3, 20.9, 20.5, 20.7, 21.1],
       [20.5, 20.6, 21. , 20.5, 20.3],
       [21. , 20.9, 21.6, 21.5, 21.4],
       [22.5, 22.4, 21.8, 22.5, 22.1],
       [22. , 22.1, 21.5, 21.3, 21.5],
       [21.1, 21.5, 21.5, 20.7, 21.2],
       [22.4, 22.2, 22.1, 22.3, 22.9],
       [20.4, 20.6, 20.8, 20.4, 21. ],
       [21.6, 20.9, 21.2, 21. , 21. ],
       [21. , 21.6, 21.5, 21. , 21.2],
       [22.2, 21.6, 21.5, 21.8, 22.3],
       [22.9, 23.3, 23.4,

In [89]:
temp_grad=np.zeros(temperatures.shape)


In [90]:
#column wise approach
for j in range(temperatures.shape[1]):  # Sensors
    for i in range(temperatures.shape[0]):  # Days
        temp_grad[i, j] = np.max(temperatures[:i+1, j]) - np.min(temperatures[:i+1, j])
        
temp_grad

array([[0. , 0. , 0. , 0. , 0. ],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [3. , 2.7, 2.3, 3. , 3. ],
       [3.1, 3.4, 3.1, 3.8, 3.3],
       [4. , 3.6, 3.1, 3.9, 3.7],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.9, 4.4, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4.2, 4

In [91]:
#Row wise approach
for i in range(1, 30):

    cum_max = np.max(temperatures[:i+1, :], axis=0)
    cum_min = np.min(temperatures[:i+1, :], axis=0)
    temp_grad[i,:]= cum_max-cum_min

temp_grad
        

array([[0. , 0. , 0. , 0. , 0. ],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [2.5, 2.4, 2.3, 2.1, 1.7],
       [3. , 2.7, 2.3, 3. , 3. ],
       [3.1, 3.4, 3.1, 3.8, 3.3],
       [4. , 3.6, 3.1, 3.9, 3.7],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.5, 3.9, 4. ],
       [4. , 3.6, 3.9, 4.4, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4. , 4.1, 4.1, 4.7, 4.1],
       [4.2, 4