In [1]:
import numpy as np


# NumPy Indexing and Slicing

NumPy provides powerful indexing and slicing capabilities for manipulating arrays efficiently. This document covers basic indexing for 1D and 2D arrays.

## 1D Array Indexing

```python
import numpy as np

# Creating a 1D NumPy array
arr = np.array([0, 1, 2, 3, 4])

# Accessing elements
print(arr[0])      # Single element: 0
print(arr[1:4])    # Slice: [1 2 3]
print(arr[:3])     # Start to index 3: [0 1 2]
print(arr[2:])     # Index 2 to end: [2 3 4]
print(arr[::2])    # Every second element: [0 2 4]
print(arr[::-1])   # Every Element but in reverse order
```

### 1D Slicing Syntax:
```plaintext
arr[start:stop:step]
```
- `start`: Starting index (inclusive, default is 0)
- `stop`: Ending index (exclusive, default is end of array)
- `step`: Step size (default is 1)

### Explanation:
- `arr[0]` returns the first element.
- `arr[1:4]` extracts elements from index 1 to 3.
- `arr[:3]` selects elements from the start up to index 2.
- `arr[2:]` selects elements from index 2 to the end.
- `arr[::2]` extracts every second element.

## 2D Array Indexing

```python
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Accessing elements and slices
print(arr_2d[0, 0])    # Element at row 0, col 0: 1
print(arr_2d[1])       # Entire row 1: [4 5 6]
print(arr_2d[:, 1])    # Entire column 1: [2 5 8]
print(arr_2d[0:2, 1:]) # Subarray: [[2 3]
                       #           [5 6]]
```

### 2D Slicing Syntax:
```plaintext
arr_2d[start_row:stop_row:step_row, start_col:stop_col:step_col]
```
- `start_row`: Starting row index (inclusive, default is 0)
- `stop_row`: Ending row index (exclusive, default is end of rows)
- `step_row`: Row step size (default is 1)
- `start_col`: Starting column index (inclusive, default is 0)
- `stop_col`: Ending column index (exclusive, default is end of columns)
- `step_col`: Column step size (default is 1)

### Explanation:
- `arr_2d[0, 0]` accesses the element at row 0, column 0.
- `arr_2d[1]` retrieves the entire second row.
- `arr_2d[:, 1]` selects the second column across all rows.
- `arr_2d[0:2, 1:]` extracts a subarray containing rows 0-1 and columns 1-end.

```



## Intermediate Slicing

In [12]:
# Negative indexing
arr = np.array([0, 1, 2, 3, 4])
print(arr[-1])      # Last element: 4
print(arr[-3:])     # Last 3 elements: [2 3 4]

# Step slicing
print(arr[::2])     # Every 2nd element: [0 2 4]
print(arr[::-1])    # Reverse array: [4 3 2 1 0]

# 2D slicing with steps
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[::2, ::2])  # Every 2nd row, every 2nd column:
                         # [[1 3]
                         #  [7 9]]

4
[2 3 4]
[0 2 4]
[4 3 2 1 0]
[[1 3]
 [7 9]]



## Fancy Indexing
Fancy indexing uses arrays or lists of indices to access multiple elements at once.

```python
# 1D fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(arr[indices])  # [20 40 50]

# 2D fancy indexing
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
row_indices = [0, 2]
col_indices = [1, 2]
print(arr_2d[row_indices, :])  # Rows 0 and 2: [[1 2 3]
                               #               [7 8 9]]
print(arr_2d[:, col_indices])  # Columns 1 and 2: [[2 3]
                               #                  [5 6]
                               #                  [8 9]]
print(arr_2d[row_indices, col_indices])  # Specific elements: [2 9]
```

### Key Points:
- Fancy indexing returns a copy, not a view.
- You can combine fancy indexing with slicing using `:`.

```




## 4. Boolean Masking
Boolean masking uses boolean arrays to filter elements based on conditions.

```python
# 1D boolean masking
arr = np.array([1, 5, 3, 8, 2])
mask = arr > 3
print(mask)       # [False  True False  True False]
print(arr[mask])  # Elements > 3: [5 8]

# Combining conditions
mask = (arr > 2) & (arr < 7)
print(arr[mask])  # Elements > 2 and < 7: [5 3]
```

### Key Points:
- Use `&` (and), `|` (or), `~` (not) for combining conditions.
- Boolean masks must match the array’s shape or be broadcastable.

## 5. Advanced Indexing Combinations
You can mix slicing, fancy indexing, and boolean masking for powerful operations.

```python
# Fancy indexing + slicing
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
rows = [0, 2]
print(arr_2d[rows, 1:])  # [[2 3]
                         #  [8 9]]
```

### Key Points:
- Advanced indexing is flexible but can be memory-intensive as it often creates copies.
- Use `.copy()` explicitly if you need to preserve the original array.

## 6. Broadcasting in Indexing
NumPy’s broadcasting rules apply to indexing operations.

```python
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Broadcasting a scalar
arr_2d[arr_2d > 3] = 10
print(arr_2d)  # [[ 1  2  3]
               #  [10 10 10]]
```

### Summary Table
| Technique         | Returns | Example             | Modifies Original? |
|------------------|---------|---------------------|--------------------|
| Basic Slicing   | View    | `arr[1:3]`          | Yes               |
| Fancy Indexing  | Copy    | `arr[[0, 2]]`       | No                |
| Boolean Masking | Copy    | `arr[arr > 5]`      | No                |
| Mixed Indexing  | Varies  | `arr[[0, 1], 1:]`   | No (if fancy used)|
```



## View vs Copy Behavior

### 1. Basic Slicing → Returns a View
```python
arr = np.array([10, 20, 30, 40, 50])

# Basic slicing (creates a view)
slice_arr = arr[1:3]  # [20, 30]
slice_arr[0] = 99      # Modifies slice

print(arr)  # Output: [10 99 30 40 50] (original array is modified)
```
✅ Conclusion: Basic slicing returns a view.

### 2. Fancy Indexing → Returns a Copy
```python
arr = np.array([10, 20, 30, 40, 50])

# Fancy indexing (creates a copy)
fancy_arr = arr[[0, 2]]  # [10, 30]
fancy_arr[0] = 99        # Modify the copy

print(arr)  # Output: [10 20 30 40 50] (original is NOT modified)
```
✅ Conclusion: Fancy indexing always returns a copy.

### 3. Boolean Masking → Returns a Copy
```python
arr = np.array([10, 20, 30, 40, 50])

# Boolean masking (creates a copy)
mask_arr = arr[arr > 20]  # [30, 40, 50]
mask_arr[0] = 99          # Modify the copy

print(arr)  # Output: [10 20 30 40 50] (original is NOT modified)
```
✅ Conclusion: Boolean masking always returns a copy.

### 4. Mixed Indexing → View or Copy (Depends)
```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Fancy indexing (rows) + slicing (columns)
mixed_arr = arr[[0, 2], 1:]  # Fancy indexing on rows → Copy

mixed_arr[0, 0] = 99  # Modify

print(arr)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]] (Original remains unchanged)
```
✅ Conclusion: If fancy indexing is used, the result is a copy.
🔸 If only slicing is used, the result would be a view.
```

