In [76]:
import numpy as np

# NumPy Array Reshaping and Flattening

## Array Reshaping
NumPy allows reshaping arrays to different dimensions without modifying the data.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped) # arr array remains the same, reshape makes a copy
```

**Output:**
```plaintext
[[1 2 3]
 [4 5 6]]
```

### Common Reshaping Methods:
- `reshape(rows, cols)`: Reshape to specified dimensions.
- `resize(rows, cols)`: Similar to `reshape` but modifies the original array.
- `arr.T`: Transposes the array.

### Example: Reshape a 3D Array
```python
arr = np.arange(12)
reshaped_3d = arr.reshape(2, 3, 2)
print(reshaped_3d)
```

**Output:**
```plaintext
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
```

### Example: Resize (Modifies Original Array)
```python
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(3, 2)
print(arr)
```

**Output:**
```plaintext
[[1 2]
 [3 4]
 [5 6]]
```
``` Python
arr = np.array([1, 2, 3, 4, 5])
resized_arr = np.resize(arr, (3,))  # New size: 3 elements
# output: [1 2 3]
arr = np.array([1, 2, 3, 4, 5])
resized_arr = np.resize(arr, (2, 3))  # 2 rows, 3 columns
print(resized_arr)

#output: 
[[1 2 3]
 [4 5 1]]
```
**Total elements needed: 6 (2 × 3). Original has 5, so it repeats 1 to fill.**

### Using -1 to auto calulate the columns
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_arr = arr.reshape(2, -1)  # 2 rows, auto-calculate columns
print(reshaped_arr)

#output
[[1 2 3 4]
 [5 6 7 8]]
 
```
**-1 tells NumPy to compute the size (8 elements ÷ 2 rows = 4 columns)**

## Ravel vs Flatten

`ravel()` and `flatten()` both convert multi-dimensional arrays into 1D arrays but behave differently:

- `ravel()`: Returns a view (modifications affect the original array if possible).
- `flatten()`: Returns a copy (modifications do NOT affect the original array).

### Example: Ravel
```python
arr = np.array([[1, 2], [3, 4]])
raveled = arr.ravel()
raveled[0] = 99
print(arr)  # Original array modified
```

**Output:**
```plaintext
[[99  2]
 [ 3  4]]
```

### Example: Flatten
```python
arr = np.array([[1, 2], [3, 4]])
flattened = arr.flatten()
flattened[0] = 100
print(arr)  # Original array NOT modified
```

**Output:**
```plaintext
[[1 2]
 [3 4]]
```

### Example: Flatten with Order
```python
arr = np.array([[1, 2], [3, 4]])
flattened_C = arr.flatten(order='C')  # Row-major (default)
flattened_F = arr.flatten(order='F')  # Column-major

print(flattened_C)
print(flattened_F)
```

**Output:**
```plaintext
[1 2 3 4]  # C-order
[1 3 2 4]  # F-order
```

## Conclusion
- Use `ravel()` for memory efficiency when you don't need a copy.
- Use `flatten()` when you require an independent copy of the array.



## Key Differences:
- `resize:` Repeats or truncates data to fit the new size.

- `reshape:` Reorganizes data, size must match.

- `pad:` Adds values (e.g., zeros) to reach the new size.

- `concatenate/vstack:` Combines arrays explicitly.



# NumPy Array Resizing Behavior

This document explains the differences between `resize()` and `np.resize()` in NumPy, focusing on when elements repeat and when they default to zero.

## Key Differences

| Method      | New Size > Original | New Size < Original | Behavior |
|------------|--------------------|--------------------|----------|
| `arr.resize()` | Fills with `0` | Truncates | Modifies in place |
| `np.resize()`  | Repeats cyclically | Truncates | Returns new array |

## Examples

### Using `arr.resize()`
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)
arr.resize((2, 4))
print(arr)
```
**Output:**
```
[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 0 0]]
```
*Fills new elements with `0`.*

### Using `np.resize()`
```python
arr = np.array([[1, 2], [3, 4]])
arr_resized = np.resize(arr, (3, 3))
print(arr_resized)
```
**Output:**
```
[[1 2 3]
 [4 1 2]
 [3 4 1]]
```
*Repeats elements cyclically.*

## When Does Repetition Occur?
Repetition occurs with `np.resize()` when the new size requires more elements than the original array contains.
```python
arr = np.array([1, 2, 3, 4])
arr_resized = np.resize(arr, (3, 2))
print(arr_resized)
```
**Output:**
```
[[1 2]
 [3 4]
 [1 2]]
```

## When Does It Default to Zero?
Defaulting to `0` happens with `arr.resize()` when increasing size.
```python
arr = np.array([1, 2, 3])
arr.resize((2, 2))
print(arr)
```
**Output:**
```
[[1 2]
 [3 0]]
```
*Extra elements are filled with `0`.*


# Reshape vs Resize in NumPy

## 🔹 `reshape()` vs `resize()`

| **Function** | **Returns** | **Modifies Original?** | **Key Notes** |
|-------------|------------|------------------------|-------------|
| **`reshape()`** | **View (if possible), Copy (if needed)** | ❌ No (if copy), ✅ Yes (if view) | Tries to return a view, but may create a copy if needed. |
| **`resize()`** | **Modifies in-place** | ✅ Yes | Changes original shape, fills extra spaces with zeros. |

---

## 1️⃣ `reshape()`: Returns a View **if possible**, Copy **if needed**

### ✅ **Example: When `reshape()` Returns a View (Modifies Original)**

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping (tries to return a view)
reshaped = arr.reshape(2, 3)  # Shape (2,3)

reshaped[0, 0] = 99  # Modify reshaped array

print(arr)  
# 🔹 Output: [99  2  3  4  5  6] (Original is modified → View)
```

### ❌ **Example: When `reshape()` Creates a Copy (Does NOT Modify Original)**

```python
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping with an incompatible memory layout (forces copy)
reshaped = arr.reshape(3, 2, order='F')  # Fortran order (column-major)

reshaped[0, 0] = 99  

print(arr)  
# 🔹 Output: [1 2 3 4 5 6] (Original is NOT modified → Copy)
```

✅ **Conclusion:**
- If possible, `reshape()` **returns a view** (modifies original).
- If needed, `reshape()` **creates a copy** (does NOT modify original).

---

## 2️⃣ `resize()`: **Always Modifies Original (In-Place)**

### ✅ **Example: `resize()` Modifies Original**

```python
arr = np.array([1, 2, 3, 4])

# Resize modifies in-place (changes shape permanently)
arr.resize(2, 3)

print(arr)
# 🔹 Output:
# [[1 2 3]
#  [4 0 0]]  (Original is modified, extra spaces filled with 0)
```

✅ **Conclusion:**
- `resize()` **modifies the array in-place** (no copy).
- If the new shape is larger, it fills extra spaces with **zeros**.

---

- **Use `reshape()`** when you need a **temporary change in shape** without modifying the original array.
- **Use `resize()`** when you want to **permanently modify** the shape of an array.




# Numpy Array Manipulation

# 1. NumPy insert

The `numpy.insert` function inserts values into an array at specified indices along a given axis.

## Syntax:
```python
numpy.insert(arr, obj, values, axis=None)
```

- **arr**: Input array where values will be inserted.
- **obj**: Index or indices before which values are inserted. Can be an integer, list, or slice.
- **values**: Values to insert (scalar or array-like, must match the shape of the insertion axis).
- **axis**: Axis along which to insert. If `None`, the array is flattened first.

## Use Cases:
- Add elements at specific positions in 1D arrays (e.g., inserting a number in a list).
- Insert rows/columns in 2D arrays (e.g., adding a new feature in a dataset).
- Modify multi-dimensional arrays selectively.

## Examples:

### 1.1 Inserting into a 1D Array
```python
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# Insert 10 before index 2
arr_inserted = np.insert(arr, 2, 10)
print("After inserting 10 at index 2:", arr_inserted)
# Output: [1 2 10 3 4]
```
**Visualization**: Imagine sliding `10` between `2` and `3`, shifting `3, 4` right.

### 1.2 Inserting Multiple Values into a 1D Array
```python
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# Insert [5, 6] before index 1
arr_inserted = np.insert(arr, 1, [5, 6])
print("After inserting [5, 6] at index 1:", arr_inserted)
# Output: [1 5 6 2 3 4]
```
**Visualization**: `5` and `6` are inserted before `2`, pushing `2, 3, 4` right.

### 1.3 Inserting into a 2D Array (Axis=0, Rows)
```python
arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", arr)

# Insert a row [5, 6] before index 1 along axis 0 (rows)
arr_inserted = np.insert(arr, 1, [5, 6], axis=0)
print("After inserting [5, 6] along axis=0:\n", arr_inserted)
```
**Output:**
```
[[1 2]
 [5 6]
 [3 4]]
```
**Visualization**: New row `[5, 6]` added between `[1, 2]` and `[3, 4]`.

### 1.4 Inserting into a 2D Array (Axis=1, Columns)
```python
arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", arr)

# Insert a column [5, 6] before index 1 along axis 1 (columns)
arr_inserted = np.insert(arr, 1, [5, 6], axis=1)
print("After inserting [5, 6] along axis=1:\n", arr_inserted)
```
**Output:**
```
[[1 5 2]
 [3 6 4]]
```
**Visualization**: New column `[5, 6]` inserted between columns `[1, 3]` and `[2, 4]`.

## Notes:
If `axis=None`, the array is flattened first:
```python
arr = np.array([[1, 2], [3, 4]])
arr_flat_insert = np.insert(arr, 2, 99)
print("Flattened insert:", arr_flat_insert)
# Output: [1 2 99 3 4]


## 2. NumPy Append

The `numpy.append` function adds values to the end of an array.

### Syntax:
```python
numpy.append(arr, values, axis=None)
```
- **arr**: Input array.
- **values**: Values to append (must be compatible with `arr`'s shape along the axis).
- **axis**: Axis along which to append. If `None`, both `arr` and `values` are flattened.

### Use Cases:
- Extend 1D arrays (like Python’s list append).
- Add rows/columns to 2D arrays (e.g., appending new data samples).

### Examples:
#### 2.1 Appending to a 1D Array
```python
import numpy as np

arr = np.array([1, 2, 3])
print("Original array:", arr)

# Append 4
arr_appended = np.append(arr, 4)
print("After appending 4:", arr_appended)
# Output: [1 2 3 4]
# Visualization: 4 added to the end.
```

#### 2.2 Appending Multiple Values to a 1D Array
```python
arr = np.array([1, 2, 3])
arr_appended = np.append(arr, [4, 5])
print("After appending [4, 5]:", arr_appended)
# Output: [1 2 3 4 5]
```

#### 2.3 Appending to a 2D Array (Axis=0, Rows)
```python
arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", arr)

# Append row [5, 6]
arr_appended = np.append(arr, [[5, 6]], axis=0)
print("After appending [5, 6] along axis=0:\n", arr_appended)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]
# Visualization: New row [5, 6] added at the bottom.
```
### If you use [5, 6] without extra [ ] for appending, NumPy flattens the entire array, causing an error or unintended results.

This is because
**Unlike insert(), np.append() expects the inserted values to already match the shape of the target axis.
If you're appending a new row, you must provide it as a 2D array ([[5, 6]] instead of [5, 6] like in insert).**

#### 2.4 Appending to a 2D Array (Axis=1, Columns)
```python
arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", arr)

# Append column [5, 6]
arr_appended = np.append(arr, [[5], [6]], axis=1)
print("After appending [5, 6] along axis=1:\n", arr_appended)
# Output:
# [[1 2 5]
#  [3 4 6]]
# Visualization: New column [5, 6] added to the right.
```

### Notes:
- **Shape mismatch raises an error:**
```python
# This will fail because [5, 6] isn’t shaped as a column
# arr_appended = np.append(arr, [5, 6], axis=1)  # ValueError
# it should be [[5,6]] as append expects to be same dimension unlike insert.
```
**But this error wont arise if we donot specify axis, np.append() also flattens by default if axis is not provided.**
```python
arr = np.array([[1, 2], [3, 4]])

# Append [5, 6] without specifying axis
arr_flattened = np.append(arr, [5, 6])  
print(arr_flattened)

#output:
[1 2 3 4 5 6]
```

## 3. NumPy Delete

The `numpy.delete` function removes elements from an array at specified indices.

#### Syntax:
```python
numpy.delete(arr, obj, axis=None)
```
- **arr**: Input array.
- **obj**: Index or indices to delete (integer, list, or slice).
- **axis**: Axis along which to delete. If `None`, the array is flattened.

#### Use Cases:
- Remove specific elements from 1D arrays.
- Delete rows/columns from 2D arrays (e.g., drop outliers from data).

### Examples:

#### 3.1 Deleting from a 1D Array
```python
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# Delete element at index 2
arr_deleted = np.delete(arr, 2)
print("After deleting index 2:", arr_deleted)
# Output: [1 2 4]
# Visualization: 3 is removed, and 4 shifts left.
```

#### 3.2 Deleting Multiple Indices from a 1D Array
```python
arr = np.array([1, 2, 3, 4, 5])
arr_deleted = np.delete(arr, [1, 3])
print("After deleting indices 1 and 3:", arr_deleted)
# Output: [1 3 5]
```

#### 3.3 Deleting a Row from a 2D Array (Axis=0)
```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Original array:\n", arr)

# Delete row at index 1
arr_deleted = np.delete(arr, 1, axis=0)
print("After deleting row 1:\n", arr_deleted)
# Output:
# [[1 2]
#  [5 6]]
# Visualization: Middle row [3, 4] is gone.
```

#### 3.4 Deleting a Column from a 2D Array (Axis=1)
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

# Delete column at index 1
arr_deleted = np.delete(arr, 1, axis=1)
print("After deleting column 1:\n", arr_deleted)
# Output:
# [[1 3]
#  [4 6]]
# Visualization: Middle column [2, 5] is removed.
```



# NumPy Concatenate

The `numpy.concatenate` function joins a sequence of arrays along an existing axis.

## Syntax

```python
numpy.concatenate((a1, a2, ...), axis=0, out=None)
```

- `(a1, a2, ...)`: Tuple or list of arrays to concatenate.
- `axis`: Axis along which to concatenate (default is `0`).
- `out`: Optional output array to store the result.

## Use Cases

- Combine multiple arrays into one (e.g., merging datasets).
- Stack arrays vertically (rows) or horizontally (columns).

## Examples

### 4.1 Concatenating 1D Arrays

```python
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr_concat = np.concatenate((arr1, arr2))
print("Concatenated array:", arr_concat)
```

**Output:**
```plaintext
[1 2 3 4]
```
**Visualization:** `arr1` and `arr2` joined end-to-end.

---

### 4.2 Concatenating 2D Arrays (Axis=0, Rows)

```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

arr_concat = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along axis=0:\n", arr_concat)
```

**Output:**
```plaintext
[[1 2]
 [3 4]
 [5 6]]
```
**Visualization:** `arr2` stacked below `arr1`.

---

### 4.3 Concatenating 2D Arrays (Axis=1, Columns)

```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
arr_concat = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along axis=1:\n", arr_concat)
```

**Output:**
```plaintext
[[1 2 5]
 [3 4 6]]
```
**Visualization:** `arr2` added as a new column to the right of `arr1`.



# Stacking (vstack, hstack, dstack)

Stacking functions provide specialized concatenation for specific axes.

## 5.1 `vstack` (Vertical Stack)

Stacks arrays along rows (`axis=0`).

```python
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr_vstack = np.vstack((arr1, arr2))
print("Vertically stacked:\n", arr_vstack)
```

**Output:**
```plaintext
[[1 2]
 [3 4]]
```
**Visualization:** `arr1` on top, `arr2` below.

---

## 5.2 `hstack` (Horizontal Stack)

Stacks arrays along columns.

```python
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr_hstack = np.hstack((arr1, arr2))
print("Horizontally stacked:", arr_hstack)
```

**Output:**
```plaintext
[1 2 3 4]
```

For 2D arrays:

```python
arr1 = np.array([[1], [2]])
arr2 = np.array([[3], [4]])
print("2D hstack:\n", np.hstack((arr1, arr2)))
```

**Output:**
```plaintext
[[1 3]
 [2 4]]
```

---

## 5.3 `dstack` (Depth Stack)

Stacks arrays along the third dimension.

```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_dstack = np.dstack((arr1, arr2))
print("Depth stacked:\n", arr_dstack)
```

**Output shape:** `(2, 2, 2)`
```plaintext
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
```



# Splitting (split, hsplit, vsplit)

Splits an array into multiple sub-arrays.

## 6.1 `split`

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr_split = np.split(arr, 3)
print("Split into 3 parts:", arr_split)
```

**Output:**
```plaintext
[array([1, 2]), array([3, 4]), array([5, 6])]
```

### 2D split along `axis=0`

```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr_split = np.split(arr, 3, axis=0)
print("2D split along axis=0:", arr_split)
```

**Output:**
```plaintext
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
```

---

## 6.2 `hsplit` (Horizontal Split)

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_hsplit = np.hsplit(arr, 3)
print("Horizontally split:\n", arr_hsplit)
```

**Output:**
```plaintext
[array([[1], [4]]), array([[2], [5]]), array([[3], [6]])]
```

---

## 6.3 `vsplit` (Vertical Split)

```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr_vsplit = np.vsplit(arr, 3)
print("Vertically split:\n", arr_vsplit)
```

**Output:**
```plaintext
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
```



#  Extra NumPy Array Manipulation Functions

## 1. NumPy `expand_dims`
Adds a new axis to an array, increasing its dimensionality.

### Syntax:
```python
numpy.expand_dims(arr, axis)
```
- `arr`: Input array.
- `axis`: Position where the new axis is added.

### Use Cases:
- Convert a 1D array to 2D (e.g., for broadcasting or model input).
- Add dimensions for compatibility in operations.

### Examples:
```python
import numpy as np

arr = np.array([1, 2, 3])
arr_expanded = np.expand_dims(arr, axis=0)
print("Expanded at axis=0:\n", arr_expanded)
# Output: [[1 2 3]]
# Shape: (1, 3)

arr_expanded = np.expand_dims(arr, axis=1)
print("Expanded at axis=1:\n", arr_expanded)
# Output:
# [[1]
#  [2]
#  [3]]
# Shape: (3, 1)
```

## 2. NumPy `squeeze`
Removes single-dimensional entries from the shape of an array.

### Syntax:
```python
numpy.squeeze(arr, axis=None)
```
- `arr`: Input array.
- `axis`: Optional; specifies which axes to squeeze (must have size 1).

### Use Cases:
- Remove unnecessary dimensions after operations like `expand_dims`.
- Simplify array shapes for readability or compatibility.

### Examples:
```python
arr = np.array([[1], [2], [3]])  # Shape: (3, 1)
arr_squeezed = np.squeeze(arr)
print("Squeezed array:", arr_squeezed)
# Output: [1 2 3]
# Shape: (3,)

arr = np.array([[[1, 2]]])  # Shape: (1, 1, 2)
arr_squeezed = np.squeeze(arr)
print("Fully squeezed:\n", arr_squeezed)
# Output: [1 2]
# Shape: (2,)
```

## 3. NumPy `transpose` / `swapaxes`
Rearranges the axes of an array.

### Syntax:
```python
numpy.transpose(arr, axes=None)  # or arr.T
numpy.swapaxes(arr, axis1, axis2)
```
- `arr`: Input array.
- `axes`: Tuple of axis indices to reorder (default reverses order).
- `axis1`, `axis2`: Axes to swap (for `swapaxes`).

### Use Cases:
- Reorient data (e.g., swap rows and columns in a matrix).
- Prepare arrays for operations requiring specific axis alignments.

### Examples:
```python
# Transpose 2D array
arr = np.array([[1, 2], [3, 4]])
arr_transposed = np.transpose(arr)
print("Transposed:\n", arr_transposed)
# Output:
# [[1 3]
#  [2 4]]

# 3D array with specific axes
arr = np.arange(8).reshape(2, 2, 2)
arr_transposed = np.transpose(arr, (1, 0, 2))
print("Transposed (1, 0, 2):\n", arr_transposed)

# Swapaxes
arr_swapped = np.swapaxes(arr, 0, 1)
print("Swapped axes 0 and 1:\n", arr_swapped)
```

## 4. NumPy `flip`
Reverses the order of elements along a specified axis.

### Syntax:
```python
numpy.flip(arr, axis=None)
```
- `arr`: Input array.
- `axis`: Axis to flip. If `None`, flips all axes.

### Use Cases:
- Reverse arrays (e.g., time series data).
- Mirror images or matrices.

### Examples:
```python
arr = np.array([1, 2, 3, 4])
arr_flipped = np.flip(arr)
print("Flipped 1D:", arr_flipped)
# Output: [4 3 2 1]

arr = np.array([[1, 2], [3, 4]])
arr_flipped = np.flip(arr, axis=0)
print("Flipped along axis=0:\n", arr_flipped)
# Output:
# [[3 4]
#  [1 2]]

arr_flipped = np.flip(arr, axis=1)
print("Flipped along axis=1:\n", arr_flipped)
# Output:
# [[2 1]
#  [4 3]]
```

## 5. NumPy `tile`
Repeats an array a specified number of times.

### Syntax:
```python
numpy.tile(arr, reps)
```
- `arr`: Input array.
- `reps`: Number of repetitions (integer or tuple for each axis).

### Use Cases:
- Create repeated patterns (e.g., for broadcasting or tiling data).
- Expand arrays systematically.

### Examples:
```python
arr = np.array([1, 2])
arr_tiled = np.tile(arr, 3)
print("Tiled 3 times:", arr_tiled)
# Output: [1 2 1 2 1 2]

arr = np.array([[1, 2], [3, 4]])
arr_tiled = np.tile(arr, (2, 1))
print("Tiled (2, 1):\n", arr_tiled)
# Output:
# [[1 2]
#  [3 4]
#  [1 2]
#  [3 4]]
```

## 6. NumPy `pad`
Pads an array with specified values along edges.

### Syntax:
```python
numpy.pad(arr, pad_width, mode='constant', **kwargs)
```
- `arr`: Input array.
- `pad_width`: Number of values to pad on each axis (tuple or int).
- `mode`: Padding method (`'constant'`, `'edge'`, `'wrap'`, etc.).
- `kwargs`: Additional arguments (e.g., `constant_values`).

### Use Cases:
- Add borders to arrays (e.g., image processing).
- Ensure arrays meet size requirements.

### Examples:
```python
arr = np.array([1, 2, 3])
arr_padded = np.pad(arr, (2, 1), mode='constant', constant_values=0)
print("Padded:", arr_padded)
# Output: [0 0 1 2 3 0]

arr = np.array([[1, 2], [3, 4]])
arr_padded = np.pad(arr, ((1, 1), (0, 1)), mode='constant', constant_values=9)
print("2D padded:\n", arr_padded)
# Output:
# [[9 9 9]
#  [1 2 9]
#  [3 4 9]
#  [9 9 9]]
```

---
