In [102]:
import numpy as np

# NumPy Array Properties

## 1. shape
**Description**  
The `shape` property returns a tuple representing the dimensions of the array (rows, columns, etc.). It describes how the array is structured.

**Example**
```python
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array Shape:", arr1.shape)

# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print("2D Array Shape:", arr2.shape)

# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array Shape:", arr3.shape)
```

**Output**
```
1D Array Shape: (4,)
2D Array Shape: (2, 2)
3D Array Shape: (2, 2, 2)
```

**Explanation**
- `(4,)`: 4 elements in a single dimension.
- `(2, 2)`: 2 rows and 2 columns.
- `(2, 2, 2)`: 2 blocks, each with 2 rows and 2 columns.

---

## 2. ndim
**Description**  
The `ndim` property returns the number of dimensions (axes) of the array.

**Example**
```python
import numpy as np

arr1 = np.array([1, 2, 3])
print("1D Array ndim:", arr1.ndim)

arr2 = np.array([[1, 2], [3, 4]])
print("2D Array ndim:", arr2.ndim)

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array ndim:", arr3.ndim)
```

**Output**
```
1D Array ndim: 1
2D Array ndim: 2
3D Array ndim: 3
```

**Explanation**
- `1`: 1D array (vector).
- `2`: 2D array (matrix).
- `3`: 3D array (tensor).

---

## 3. dtype
**Description**  
The `dtype` property returns the data type of the array's elements (e.g., `int32`, `float64`, `bool`).

**Example**
```python
import numpy as np

arr1 = np.array([1, 2, 3])
print("Integer Array dtype:", arr1.dtype)

arr2 = np.array([1.5, 2.7, 3.2])
print("Float Array dtype:", arr2.dtype)

test_arr= np.array([1,2,3,4,5.2]).dtype
print("Even if one value is float it's dtype is float",test_arr.dtype)
arr3 = np.array([True, False])
print("Boolean Array dtype:", arr3.dtype)
```

**Output**
```
Integer Array dtype: int64
Float Array dtype: float64
Test Array dtype: float64
Boolean Array dtype: bool
```

**Explanation**
- `int64`: 64-bit integer.
- `float64`: 64-bit floating-point number.
- `bool`: Boolean (True/False).

---

## 4. size
**Description**  
The `size` property returns the total number of elements in the array.

**Example**
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array size:", arr.size)
```

**Output**
```
Array size: 6
```

**Explanation**
- The array has 6 elements (2 rows × 3 columns).

---

## 5. itemsize
**Description**  
The `itemsize` property returns the size in bytes of each element in the array.

**Example**
```python
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Item size in bytes:", arr.itemsize)
```

**Output**
```
Item size in bytes: 4
```

**Explanation**
- Each `int32` element occupies 4 bytes in memory.

---

## 6. nbytes
**Description**  
The `nbytes` property returns the total memory consumed by the array in bytes.

**Example**
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print("Total bytes used:", arr.nbytes)
```

**Output**
```
Total bytes used: 48
```

**Explanation**
- Each `float64` element takes 8 bytes.
- 6 elements × 8 bytes = 48 bytes.

---

## 7. T (Transpose)
**Description**  
The `T` property returns the transposed version of the array (rows and columns swapped).

**Example**
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(arr)
print("Transposed array:")
print(arr.T)
```

**Output**
```
Original array:
[[1 2 3]
 [4 5 6]]

Transposed array:
[[1 4]
 [2 5]
 [3 6]]
```

**Explanation**
- Rows become columns, and columns become rows.

---

## 8. flat
**Description**  
The `flat` property returns a 1D iterator over all elements in the array.

**Example**
```python
import numpy as np

arr = np.array([[1, 2], [3, 4]])
for elem in arr.flat:
    print(elem, end=' ')
```

**Output**
```
1 2 3 4
```

**Explanation**
- The `flat` iterator allows iteration over all elements in a single dimension.

---

## Summary Table

| Property  | Description                 | Example Output |
|-----------|-----------------------------|---------------|
| shape     | Tuple of dimensions         | (2, 3)        |
| ndim      | Number of dimensions        | 2             |
| dtype     | Data type of elements       | float64       |
| size      | Total number of elements    | 6             |
| itemsize  | Bytes per element           | 8             |
| nbytes    | Total bytes used            | 48            |
| T         | Transpose of array          | [[1 4] [2 5]] |
| flat      | 1D iterator over elements   | [1, 2, 3, 4]  |



## What is `itemsize`?

### Definition
The `itemsize` property of a NumPy array returns the size, in bytes, of each individual element in the array. It is directly tied to the array's data type (`dtype`), which determines how much memory each element occupies. This property is crucial for understanding memory consumption and optimizing performance in numerical computations.

### Key Points
- **Unit**: Measured in bytes (1 byte = 8 bits).
- **Dependence on `dtype`**: The value of `itemsize` depends on the data type specified when the array is created (e.g., `int32`, `float64`, `uint8`).
- **Fixed Size**: Unlike Python's built-in types (e.g., lists), NumPy arrays use fixed-size data types, making `itemsize` consistent for all elements in the array.

### How Does `itemsize` Work?
NumPy uses C-style memory allocation under the hood, where each element in an array is stored in a contiguous block of memory. The `itemsize` represents the number of bytes allocated for each element based on its `dtype`. For example:

- An `int32` (32-bit integer) takes **4 bytes** because 32 bits ÷ 8 bits/byte = 4 bytes.
- A `float64` (64-bit floating-point number) takes **8 bytes** because 64 bits ÷ 8 bits/byte = 8 bytes.

The total memory used by the array can be calculated as:

```
Total Memory (in bytes) = size * itemsize
```

where `size` is the total number of elements in the array, and this total is reflected in the `nbytes` property.

## Examples of `itemsize`

### Example 1: Basic Data Types

```python
import numpy as np

# Array with int32 data type
arr1 = np.array([1, 2, 3], dtype=np.int32)
print("int32 Array itemsize:", arr1.itemsize, "bytes")

# Array with float64 data type
arr2 = np.array([1.5, 2.7, 3.2], dtype=np.float64)
print("float64 Array itemsize:", arr2.itemsize, "bytes")

# Array with uint8 data type (unsigned 8-bit integer)
arr3 = np.array([255, 0, 100], dtype=np.uint8)
print("uint8 Array itemsize:", arr3.itemsize, "bytes")
```

**Output**:
```
int32 Array itemsize: 4 bytes
float64 Array itemsize: 8 bytes
uint8 Array itemsize: 1 byte
```

**Explanation**:
- `int32`: 32 bits = 4 bytes.
- `float64`: 64 bits = 8 bytes.
- `uint8`: 8 bits = 1 byte (useful for small integers, like pixel values in images).

---

### Example 2: Complex Data Types

```python
import numpy as np

# Array with complex64 data type (32-bit real + 32-bit imaginary)
arr4 = np.array([1+2j, 3+4j], dtype=np.complex64)
print("complex64 Array itemsize:", arr4.itemsize, "bytes")

# Array with complex128 data type (64-bit real + 64-bit imaginary)
arr5 = np.array([1+2j, 3+4j], dtype=np.complex128)
print("complex128 Array itemsize:", arr5.itemsize, "bytes")
```

**Output**:
```
complex64 Array itemsize: 8 bytes
complex128 Array itemsize: 16 bytes
```

**Explanation**:
- `complex64`: 32 bits for real part + 32 bits for imaginary part = 64 bits = **8 bytes**.
- `complex128`: 64 bits for real part + 64 bits for imaginary part = 128 bits = **16 bytes**.

---

### Example 3: Strings and Unicode

```python
import numpy as np

# Array with fixed-length string (U4 = Unicode string of max length 4)
arr6 = np.array(["cat", "dog"], dtype="U4")
print("U4 Array itemsize:", arr6.itemsize, "bytes")
```

**Output**:
```
U4 Array itemsize: 16 bytes
```

**Explanation**:
- `U4` means each element is a Unicode string with a maximum length of **4 characters**.
- Each Unicode character in NumPy is stored as **4 bytes** (UTF-32 encoding), so `U4 = 4 characters * 4 bytes/character = 16 bytes` per element.
- Even if the string is shorter (e.g., "cat" is 3 characters), the full allocated space (16 bytes) is used.

---

## Practical Implications

### **Memory Optimization**:
- Choosing a **smaller `dtype`** (e.g., `int8` instead of `int64`) reduces `itemsize`, saving memory when large arrays are involved.
- Example: An array of **1 million elements** with `int8` (**1 byte**) uses **1 MB**, while `int64` (**8 bytes**) uses **8 MB**.

### **Performance**:
- Smaller `itemsize` values can improve **cache efficiency** and **computation speed**, especially in large-scale numerical operations.

### **Data Range Limitations**:
- The `itemsize` is tied to the **range of values** a `dtype` can represent:
  - `uint8`: **0 to 255** (1 byte).
  - `int32`: **-2,147,483,648 to 2,147,483,647** (4 bytes).
- Choosing an inappropriate `dtype` can lead to **overflow or truncation**.

## Relationship with Other Properties

- **`size`**: The total number of elements in the array. Multiply `size` by `itemsize` to get the total memory usage (`nbytes`).
- **`nbytes`**: Total memory in bytes (`size * itemsize`).
- **`dtype`**: Determines the `itemsize`. Changing the `dtype` via `astype` alters the `itemsize`.

### Example Combining Properties

```python
import numpy as np

arr = np.array([[1, 2], [3, 4]], dtype=np.int16)
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize, "bytes")
print("size:", arr.size)
print("nbytes:", arr.nbytes, "bytes")
```

**Output**:
```
dtype: int16
itemsize: 2 bytes
size: 4
nbytes: 8 bytes
```

**Explanation**:
- `int16`: **16 bits = 2 bytes** per element.
- `size`: **4 elements** (2x2 array).
- `nbytes`: **4 elements * 2 bytes = 8 bytes**.

---

## Common Data Types and Their `itemsize`

| Data Type  | Description                 | `itemsize` (bytes) |
|------------|----------------------------|-------------------|
| `int8`     | 8-bit integer               | 1                 |
| `uint8`    | Unsigned 8-bit integer      | 1                 |
| `int16`    | 16-bit integer              | 2                 |
| `int32`    | 32-bit integer              | 4                 |
| `int64`    | 64-bit integer              | 8                 |
| `float32`  | 32-bit float                | 4                 |
| `float64`  | 64-bit float                | 8                 |
| `complex64`  | 32-bit real + 32-bit imag  | 8                 |
| `complex128` | 64-bit real + 64-bit imag | 16                |
| `U4`       | Unicode string (max 4 chars)| 16                |


## Understanding Array Operations

In [106]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a",a)
print("b",b)

a [20 30 40 50]
b [0 1 2 3]


In [107]:
a-b

array([20, 29, 38, 47])

In [108]:
# c = a-np.array([2,4]) # ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [109]:
b**2

array([0, 1, 4, 9])

In [110]:
10* np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [111]:
a<35

array([ True,  True, False, False])

**Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:**

In [113]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A)
B

[[1 1]
 [0 1]]


array([[2, 0],
       [3, 4]])

In [114]:
A*B   # elementwise product

array([[2, 0],
       [0, 4]])

In [115]:
A @ B # Matrix Product
# This is similar to
np.dot(A,B)

array([[5, 4],
       [3, 4]])

## Example: Matrix Multiplication

### ✅ Valid Multiplication  
Let’s say we have two matrices:

**Matrix A (2×2):**  
$$
A =
\begin{bmatrix}
1 & 2 \\ 
3 & 4
\end{bmatrix}
$$

**Matrix B (2×2):**  
$$
B =
\begin{bmatrix}
5 & 6 \\ 
7 & 8
\end{bmatrix}
$$

#### Multiplication:  
$$
C = A \times B =
\begin{bmatrix}
(1 \times 5 + 2 \times 7) & (1 \times 6 + 2 \times 8) \\ 
(3 \times 5 + 4 \times 7) & (3 \times 6 + 4 \times 8)
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
19 & 22 \\ 
43 & 50
\end{bmatrix}
$$

---

### ❌ Invalid Multiplication  
If we have:

**Matrix A (2×3):**  
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6
\end{bmatrix}
$$

**Matrix B (4×2):**  
$$
B =
\begin{bmatrix}
1 & 2 \\ 
3 & 4 \\ 
5 & 6 \\ 
7 & 8
\end{bmatrix}
$$

Multiplication is **not possible** because the number of columns in \( A \) (**3**) does not match the number of rows in \( B \) (**4**).  

In matrix multiplication, the **inner dimensions must match** for the operation to be valid.


In [117]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(b / a)  # [4.  2.5 2. ]
print(a ** 2) # [1 4 9]
# Also scalar operations like
print(a * 2)  # [2 4 6]
print(a + 10) # [11 12 13]

[5 7 9]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[2 4 6]
[11 12 13]


# NumPy Universal Functions (ufuncs)

NumPy provides **universal functions** that operate **element-wise** on arrays.  
These functions are **optimized** and **vectorized**, making them much faster than Python loops.

## 🔢 Math Functions

- `np.add(a, b)`: **Addition**  
- `np.subtract(a, b)`: **Subtraction**  
- `np.multiply(a, b)`: **Multiplication**  
- `np.divide(a, b)`: **Division**  
- `np.power(a, 2)`: **Exponentiation**  
- `np.sqrt(a)`: **Square root**  
- `np.exp(a)`: **Exponential** (eˣ)  
- `np.log(a)`: **Natural logarithm**  
- `np.sin(a)`, `np.cos(a)`, etc.: **Trigonometric functions**  


# 🔢 NumPy Comparison & Logical Operations

## 🔍 Comparison Operators

| Operator | Description |
|----------|-------------|
| `>`  | Greater than |
| `<`  | Less than |
| `==` | Equal to |
| `!=` | Not equal |
| `>=` | Greater than or equal |
| `<=` | Less than or equal |

These operations return **boolean arrays**:

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(a > b)  # [False False  True]
print(a == b) # [False  True  False]


# 🔗 Logical Operations in NumPy

## 📌 Logical Functions

| Function                 | Description                     |
|--------------------------|---------------------------------|
| `np.logical_and(a, b)`   | Element-wise logical AND       |
| `np.logical_or(a, b)`    | Element-wise logical OR        |
| `np.logical_not(a)`      | Element-wise logical NOT       |
| `np.logical_xor(a, b)`   | Element-wise logical XOR       |

### ✨ Example:
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(np.logical_and(a > 1, b == 2))  # [False  True  True]

print(np.logical_or(a > 2, b < 2))    # [False False  True]
print(np.logical_not(a > 1))          # [ True False False]
```
# ⚡ Alternative: Bitwise Logical Operators

Instead of using `np.logical_*`, you can use **bitwise operators** (`&`, `|`, `~`, `^`) for element-wise operations:

## 📌 Equivalent Bitwise Operators

| NumPy Function           | Equivalent Bitwise Operator |
|--------------------------|----------------------------|
| `np.logical_and(a, b)`   | `a & b`                    |
| `np.logical_or(a, b)`    | `a \| b`                   |
| `np.logical_not(a)`      | `~a`                       |
| `np.logical_xor(a, b)`   | `a ^ b`                    |

---

## ✨ Example using Bitwise Operators:
```python
import numpy as np

x = np.array([True, False, True])
y = np.array([False, False, True])

print(x & y)  # [False False  True]  (AND)
print(x | y)  # [ True False  True]  (OR)
print(~x)     # [False  True False]  (NOT)
print(x ^ y)  # [ True False False]  (XOR)
```
**if a and b:  # ❌ This raises an error for NumPy arrays**
## 🖥️ Output:

[False False  True]
[ True False  True]
[False  True False]
[ True False False]

# Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the larger one.

## Rules
- Arrays with fewer dimensions are padded with ones on the left.
- Arrays are compatible if their shapes match or one dimension is 1.
- The smaller array is "broadcast" across the larger one.

## Example:

```python
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
B = np.array([[1], [2]])  # Shape (2,1), will be broadcast to (2,3)

result = A * B
print(result)
```

### Output:
```plaintext
[[ 1  2  3]
 [ 8 10 12]]
```

In this example, `B` is broadcasted to match the shape of `A`, and element-wise multiplication is performed.



In [122]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([10, 20,30])            # Shape (3,)
print(a + b)  # [[11 22 33] [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [123]:
a*b

array([[ 10,  40,  90],
       [ 40, 100, 180]])



## What is Broadcasting?

Broadcasting is a set of rules for applying binary universal functions (ufuncs) on arrays of different shapes. It lets you perform element-wise operations without having to manually reshape or replicate arrays.

---

## Rules for Broadcasting


## 1. Trailing Dimensions Matching

**Explanation:**  
When comparing two arrays, NumPy starts with the trailing (rightmost) dimensions and works its way left. For each pair of dimensions, they are considered compatible if either:
- The dimensions are equal, or
- One of the dimensions is 1.

**Example 1:**  
Consider an array `A` of shape `(4, 3)` and a 1D array `B` of shape `(3,)`:

```python
import numpy as np

# Array A: shape (4, 3)
A = np.arange(12).reshape(4, 3)
# Array B: shape (3,)
B = np.array([10, 20, 30])

print("Shape of A:", A.shape)  # (4, 3)
print("Shape of B:", B.shape)  # (3,)

# Broadcasting: B is treated as if its shape is (1, 3) and then stretched to (4, 3)
result = A + B
print(result)
```
## 2. Padding with Ones

**Explanation:**
If one array has fewer dimensions than the other, NumPy pads its shape on the left with ones. This "virtual" padding makes the shapes compatible for broadcasting. Essentially, a lower-dimensional array is treated as if it has extra dimensions of size 1, allowing it to "stretch" to match the higher-dimensional array.

**Example 2:**
A 1D array `C` with shape `(3,)` is treated as if it has shape `(1, 3)` when combined with a 2D array.

```python
import numpy as np

# Array C: shape (3,)
C = np.array([1, 2, 3])
# Array D: shape (2, 1)
D = np.array([[10],
              [20]])

print("Shape of C:", C.shape)  # (3,)
print("Shape of D:", D.shape)  # (2, 1)

# Broadcasting: C is padded to shape (1, 3) and D to shape (2, 1),
# resulting in an output shape of (2, 3)
result = C + D
print(result)
```
**output: This will return a array of the larger dimension array**
```
[[11 12 13]
 [21 22 23]]
```
3. **Compatibility Condition:**
   - Two dimensions are compatible if:
     - They are equal, or
     - One of them is 1.
   - If these conditions are not met for any dimension, NumPy will raise a `ValueError` indicating that the arrays are not broadcastable.

---

## Types of Broadcasting

### 1. Scalar Broadcasting
- **Description:** A scalar (a single number) is broadcast to every element of an array.
- **Example:**
  ```python
  import numpy as np
  a = np.array([1, 2, 3])
  result = a + 5  # 5 is broadcast to each element
  print(result)   # Output: [6 7 8]
  ```

## 2. Vector Broadcasting

**Definition:**  
A one-dimensional array (vector) can be broadcast across a multi-dimensional array if its shape aligns with one of the dimensions. This means the vector will be "stretched" along the appropriate axis to match the shape of the other array.

**Example:**
```python
import numpy as np

# Vector broadcasting: The 1D array B is added to each row of A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # Shape: (2, 3)
B = np.array([10, 20, 30])  # Shape: (3,)
result = A + B  
print(result)
# Expected Output:
# [[11, 22, 33],
#  [14, 25, 36]]

```
## 3 Multi- Dimension Broadcasting


### ✅ **Broadcasting a 1D Array to a 2D Array**
```python
import numpy as np

# Array C is 1D with shape (3,)
C = np.array([1, 2, 3])

# Array D is 2D with shape (2, 1)
D = np.array([[10],
              [20]])

# NumPy automatically broadcasts C to shape (2, 3) and performs element-wise addition
result = C + D

print(result)

# Output
[[11 12 13]
 [21 22 23]]

In [125]:
# Array E: shape (4, 3)
E = np.ones((4, 3))
# Array F: shape (4, 2)
F = np.ones((4, 2))

In [126]:
print(E,"\n")
print(F)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# Broadcasting Incompatibility Example

Consider the following two arrays:

- **Array E (shape: (4, 3))**
**output**

  ```
        [[1. 1. 1.]
         [1. 1. 1.]
         [1. 1. 1.]
         [1. 1. 1.]] 
  ```
- **Array F (shape: (4, 2))**
**output**

```
        [[1. 1.]
         [1. 1.]
         [1. 1.]
         [1. 1.]]
```

These arrays are **not broadcastable** because their second dimensions differ (3 vs. 2) and neither dimension is 1. In order for two arrays to be broadcast together, each pair of corresponding dimensions (when comparing from the trailing side) must either be equal or one of them must be 1.

---

## Code Example

```python
import numpy as np

# Array E: shape (4, 3)
E = np.ones((4, 3))
# Array F: shape (4, 2)
F = np.ones((4, 2))

# Attempting to add E and F will raise a ValueError because their shapes are incompatible.
try:
  result = E + F
except ValueError as err:
  print("Error:", err)



# Aggregation Operations in NumPy

NumPy provides various aggregation functions that allow you to summarize and analyze data efficiently. These functions compute statistics such as sum, mean, median, standard deviation, minimum, maximum, and product of array elements.

---

## Common Aggregation Functions

- **`np.sum(arr)`**: Returns the sum of all elements in the array.
- **`np.mean(arr)`**: Returns the mean (average) of the array elements.
- **`np.median(arr)`**: Returns the median value of the array elements.
- **`np.std(arr)`**: Returns the standard deviation of the array.
- **`np.min(arr)` / `np.max(arr)`**: Return the minimum or maximum element in the array, respectively.
- **`np.prod(arr)`**: Returns the product of all elements in the array.

---

## Example Array

Consider the following 2D array:

```python
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])
print(np.sum(arr))  # Output: 10
print(np.mean(arr))  # Output: 2.5
print(np.median(arr))  # Output: 2.5
print(np.std(arr))  # Output: 1.118033988749895 (approx.)
print(np.min(arr))  # Output: 1
print(np.max(arr))  # Output: 4
print(np.prod(arr))  # Output: 24
```

## Aggregation with the axis Parameter

The axis parameter lets you specify the direction along which the aggregation is performed:

- **`axis=0`**: Operates along the columns (aggregates each column).
- **`axis=1`**: Operates along the rows (aggregates each row).

### Examples:
``` python
print(np.max(arr, axis=0))  # Output: [3 4]
print(np.sum(arr, axis=1))  # Output: [3 7]
print(np.mean(arr, axis=0))  # Output: [2. 3.]
print(np.std(arr, axis=1))  # Output: [0.5 0.5] (approximately)

```