In [2]:
import numpy as np

# NumPy Guide: Saving and Loading Objects

## Introduction

When working with NumPy, you will often need to save arrays to disk and reload them later. NumPy provides several functions for this purpose, including:

- `np.save` and `np.load` for saving and loading single arrays in binary format (.npy)
- `np.savez` and `np.savez_compressed` for saving multiple arrays in a single file (.npz)
- `np.savetxt` and `np.loadtxt` for working with text-based storage

This guide explores each method in detail with examples and expected outputs.

---

## 1. Saving and Loading Single Arrays (`.npy` format)

### `np.save()`

Use `np.save()` to save a single NumPy array in binary format (.npy). This format preserves the data type and shape, ensuring accurate retrieval later.

### Example:

```python
import numpy as np

# Creating an array
data = np.array([[1, 2, 3], [4, 5, 6]])

# Saving the array
data_filename = "array.npy"
np.save(data_filename, data)
print(f"Array saved as {data_filename}")
```

### `np.load()`

Use `np.load()` to load an `.npy` file.

```python
# Loading the saved array
loaded_data = np.load("array.npy")
print("Loaded Data:")
print(loaded_data)
```

### Output:
```
Array saved as array.npy
Loaded Data:
[[1 2 3]
 [4 5 6]]
```

---

## 2. Saving and Loading Multiple Arrays (`.npz` format)

### `np.savez()`

Use `np.savez()` to store multiple arrays in a single file.

### Example:

```python
# Creating multiple arrays
data1 = np.array([10, 20, 30])
data2 = np.array([[1, 2], [3, 4]])

# Saving multiple arrays
np.savez("multiple_arrays.npz", array1=data1, array2=data2)
print("Multiple arrays saved.")
```

### `np.load()` for `.npz`

```python
# Loading multiple arrays
loaded = np.load("multiple_arrays.npz")

print("Array 1:", loaded["array1"])
print("Array 2:")
print(loaded["array2"])
```
**you can use np.load("file.npz").files** to see all the array names that are saved and  acess accordingly by their name
### Output:
```
Multiple arrays saved.
Array 1: [10 20 30]
Array 2:
[[1 2]
 [3 4]]
```

---

## 3. Saving and Loading Text Files (`.txt` format)

### `np.savetxt()`

Use `np.savetxt()` to save arrays in human-readable text format. This is useful for interoperability with other tools that may not support `.npy` or `.npz`.

### Example:

```python
# Creating a float array
data = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

# Saving as a text file
np.savetxt("array.txt", data, delimiter=",", fmt="%.2f")
print("Array saved as text.")
```
**You can also pass the tupe of arrays to store multiple arrays. For further info see documentation using help(savetxt)
### `np.loadtxt()`

Use `np.loadtxt()` to load data from a text file.

```python
# Loading from a text file
loaded_data = np.loadtxt("array.txt", delimiter=",")
print("Loaded Data:")
print(loaded_data)
```

### Output:
```
Array saved as text.
Loaded Data:
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
```

---

## 4. Compressed Storage (`.npz` format)

For large arrays, use `np.savez_compressed()` to reduce file size.

### Example:

```python
# Saving compressed arrays
np.savez_compressed("compressed.npz", array1=data1, array2=data2)
print("Compressed arrays saved.")
```

### Output:
```
Compressed arrays saved.
```

This reduces disk space usage while preserving data integrity.

---

## Conclusion

- Use `.npy` for saving single arrays efficiently.
- Use `.npz` when storing multiple arrays.
- Use `.savetxt` when human readability or compatibility with other programs is required.
- Use `.npz_compressed` for large datasets to save space.



In [7]:
# Creating an array
data = np.array([[1, 2, 3], [4, 5, 6]])

# Saving the array
data_filename = "array.npy"
np.save(data_filename, data)
print(f"Array saved as {data_filename}")

Array saved as array.npy


In [11]:
# Loading the saved array
loaded_data = np.load("array.npy")
print("Loaded Data:")
print(loaded_data)

Loaded Data:
[[1 2 3]
 [4 5 6]]


In [19]:
data1 = np.array([10, 20, 30])
data2 = np.array([[1, 2], [3, 4]])

# Saving multiple arrays
np.savez("multiple_arrays.npz", x1=data1, x2=data2)
print("Multiple arrays saved.")

Multiple arrays saved.


In [25]:
loaded = np.load("multiple_arrays.npz")

print("Array 1:", loaded["x1"])
print("Array 2:")
print(loaded["x2"])
loaded.files

Array 1: [10 20 30]
Array 2:
[[1 2]
 [3 4]]


['x1', 'x2']

In [30]:
# Creating a float array
data = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

# Saving as a text file
np.savetxt("array.txt", data, delimiter=",", fmt="%.2f")
print("Array saved as text.")

Array saved as text.


In [33]:
loaded_data = np.loadtxt("array.txt", delimiter=",")
print("Loaded Data:")
print(loaded_data)

Loaded Data:
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
